# Generated by Django 5.2.4 on 2026-01-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='available_barangays',
            field=models.ManyToManyField(blank=True, help_text='Leave empty for global reward. Select specific barangays to restrict availability.', related_name='available_rewards', to='accounts.barangay'),
        ),
    ]
