# Generated by Django 5.2.4 on 2026-01-27 03:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGameCooldown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_type', models.CharField(choices=[('quiz', 'Quiz Game'), ('drag_drop', 'Drag & Drop Game')], help_text='Type of game (quiz or drag_drop)', max_length=20)),
                ('last_played_at', models.DateTimeField(auto_now=True, help_text='When the user last completed this game')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Game Cooldown',
                'verbose_name_plural': 'User Game Cooldowns',
                'ordering': ['-last_played_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_name',
            field=models.CharField(blank=True, help_text='User-friendly game name for display', max_length=100),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('quiz', 'Quiz Game'), ('drag_drop', 'Drag & Drop Game')], default='drag_drop', help_text='Type of game played (quiz or drag_drop)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user', 'game_type', '-completed_at'], name='game_gamese_user_id_db59e3_idx'),
        ),
        migrations.AddField(
            model_name='usergamecooldown',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_cooldowns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usergamecooldown',
            unique_together={('user', 'game_type')},
        ),
    ]
